In [1]:
import os
import time
import json
import parse
import fasttext
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
plt.style.use(["science", "no-latex"])
from utils import *
from sklearn.metrics import f1_score

files = !ls backup*.txt


df = pd.concat(
    [read_record(file) for file in [
    #"backup_12.txt",
    #"backup_12_1.txt",
    #"backup_12_2.txt",
    # "backup_17.txt",
    # "backup_17__2.txt",
    # "backup_18.txt",
    # "backup_18_2.txt",
    # "backup_20.txt",
    # "backup_20_2.txt",
    # "backup_20.txt",
    # "backup_20_2.txt",
    "backup_23.txt",
    # "backup_23_1.txt",
    ]], ignore_index=True)

In [4]:
df.groupby("train,eval".split(",")).agg(["mean", "std","count"])

                  microF1              macroF1
                     mean    std count    mean    std count
train  eval
xlm_dd dev_dd       0.597  0.018     5   0.524  0.031     5
       devtest_dd   0.611  0.011     5   0.575  0.017     5
       test_dd      0.625  0.015     5   0.577  0.018     5